<?php
function getQuestions($examId) {
    $allExams = [

    'it_fundamentals' => [
      ['q'=>'What does CPU stand for?','opts'=>['Central Processing Unit','Computer Personal Unit','Central Program Utility','Core Processing Utility'],'ans'=>0],
      ['q'=>'Which component stores data temporarily while a computer is running?','opts'=>['Hard Drive','SSD','RAM','ROM'],'ans'=>2],
      ['q'=>'What type of software manages hardware resources and provides services to programs?','opts'=>['Application Software','Operating System','Utility Software','Firmware'],'ans'=>1],
      ['q'=>'Which bus is commonly used to connect a graphics card to a motherboard?','opts'=>['USB','PCI Express','SATA','IDE'],'ans'=>1],
      ['q'=>'What does BIOS stand for?','opts'=>['Basic Input/Output System','Binary Input Output Storage','Basic Internal Operating System','Binary Internal Output System'],'ans'=>0],
      ['q'=>'Which storage device has no moving parts?','opts'=>['HDD','Floppy Disk','CD-ROM','SSD'],'ans'=>3],
      ['q'=>'What is the primary function of a power supply unit (PSU)?','opts'=>['Store data','Convert AC to DC power','Cool the CPU','Connect peripherals'],'ans'=>1],
      ['q'=>'Which of the following is an input device?','opts'=>['Monitor','Printer','Scanner','Speaker'],'ans'=>2],
      ['q'=>'What does GPU stand for?','opts'=>['General Processing Unit','Graphics Processing Unit','Global Program Utility','Graphic Program Unit'],'ans'=>1],
      ['q'=>'Which file system is natively used by Windows?','opts'=>['ext4','HFS+','NTFS','FAT16'],'ans'=>2],
      ['q'=>'What is the function of a heat sink?','opts'=>['Increase CPU speed','Dissipate heat away from components','Store temporary data','Provide power to the CPU'],'ans'=>1],
      ['q'=>'Which connector is used to connect a SATA hard drive?','opts'=>['IDE','Molex','SATA','eSATA'],'ans'=>2],
      ['q'=>'What does USB stand for?','opts'=>['Universal Serial Bus','Unified System Bus','Universal System Board','Unified Serial Bridge'],'ans'=>0],
      ['q'=>'Which type of memory retains data even when power is off?','opts'=>['RAM','Cache','DRAM','ROM'],'ans'=>3],
      ['q'=>'What is the clock speed of a CPU measured in?','opts'=>['Bytes','Hertz','Watts','Volts'],'ans'=>1],
      ['q'=>'Which operating system is open-source?','opts'=>['Windows 10','macOS Ventura','Ubuntu Linux','Chrome OS (old)'],'ans'=>2],
      ['q'=>'What does the term "64-bit" refer to in a processor?','opts'=>['The number of cores','The data bus width','The cache size','The clock speed'],'ans'=>1],
      ['q'=>'Which port is commonly used for connecting a monitor?','opts'=>['USB-A','RJ-45','HDMI','PS/2'],'ans'=>2],
      ['q'=>'What is virtual memory?','opts'=>['RAM installed on the GPU','Extra cache on the CPU','A portion of the hard drive used as RAM','Cloud-based storage'],'ans'=>2],
      ['q'=>'Which device converts digital signals to analog for telephone lines?','opts'=>['Router','Switch','Hub','Modem'],'ans'=>3],
      ['q'=>'What does POST stand for in computing?','opts'=>['Power On Self Test','Program Operating System Test','Power Output System Test','Peripheral Output Self Test'],'ans'=>0],
      ['q'=>'Which type of display panel offers the best color accuracy?','opts'=>['TN','VA','IPS','OLED (standard LCD choice)'],'ans'=>2],
      ['q'=>'What is the purpose of a driver in a computer system?','opts'=>['Speed up the CPU','Allow OS to communicate with hardware','Store system files','Manage network traffic'],'ans'=>1],
      ['q'=>'Which keyboard shortcut is used to copy in Windows?','opts'=>['Ctrl+X','Ctrl+V','Ctrl+C','Ctrl+Z'],'ans'=>2],
      ['q'=>'What is the default port for HTTP?','opts'=>['21','443','80','25'],'ans'=>2],
      ['q'=>'Which component controls data flow between the CPU and other components?','opts'=>['Power Supply','Chipset','RAM','GPU'],'ans'=>1],
      ['q'=>'What does HDMI stand for?','opts'=>['High Definition Media Interface','High Density Monitor Interface','High Definition Multimedia Interface','High Data Multimedia Interface'],'ans'=>2],
      ['q'=>'What is the purpose of a UPS (Uninterruptible Power Supply)?','opts'=>['Speed up the computer','Provide backup power during outages','Cool the components','Increase internet speed'],'ans'=>1],
      ['q'=>'Which task manager shortcut opens in Windows?','opts'=>['Ctrl+Alt+Delete','Ctrl+Shift+Esc','Both A and B','Alt+Tab'],'ans'=>2],
      ['q'=>'What type of cable is used for gigabit ethernet?','opts'=>['Cat5','Cat5e','Cat6','Coaxial'],'ans'=>2],
      ['q'=>'Which storage interface offers the fastest data transfer?','opts'=>['SATA III','USB 3.0','NVMe PCIe','eSATA'],'ans'=>2],
      ['q'=>'What does RAID stand for?','opts'=>['Redundant Array of Independent Disks','Random Access Input Device','Rapid Access Information Drive','Redundant Array of Internal Drives'],'ans'=>0],
      ['q'=>'Which process converts a domain name to an IP address?','opts'=>['DHCP','FTP','DNS','NAT'],'ans'=>2],
      ['q'=>'What is the main job of an antivirus program?','opts'=>['Speed up the computer','Back up files','Detect and remove malware','Manage device drivers'],'ans'=>2],
      ['q'=>'Which generation of USB allows data transfer up to 10 Gbps?','opts'=>['USB 2.0','USB 3.0','USB 3.1 Gen 2','USB 1.1'],'ans'=>2],
      ['q'=>'What does "formatting" a drive mean?','opts'=>['Defragmenting the drive','Preparing a drive for use by creating a file system','Encrypting the drive','Cloning the drive'],'ans'=>1],
      ['q'=>'Which component is responsible for long-term data storage?','opts'=>['RAM','Cache','CPU registers','Hard Drive'],'ans'=>3],
      ['q'=>'What is the function of an operating system\'s kernel?','opts'=>['Manage the user interface','Manage hardware resources at the lowest level','Run application programs','Handle internet connections'],'ans'=>1],
      ['q'=>'Which protocol assigns IP addresses automatically?','opts'=>['DNS','HTTP','DHCP','FTP'],'ans'=>2],
      ['q'=>'What does "overclocking" a CPU mean?','opts'=>['Running it below its rated speed','Running it at a higher speed than rated','Replacing it with a newer model','Disabling its cores'],'ans'=>1],
      ['q'=>'What type of connector does a standard PS/2 keyboard use?','opts'=>['USB-A','6-pin mini-DIN','RJ-45','DB-9'],'ans'=>1],
      ['q'=>'Which file extension is associated with executable files in Windows?','opts'=>['.txt','.dll','.exe','.bat'],'ans'=>2],
      ['q'=>'What does "defragmentation" do to a hard drive?','opts'=>['Removes viruses','Reorganizes fragmented files for faster access','Erases all data','Compresses files'],'ans'=>1],
      ['q'=>'Which type of RAM is most commonly used in modern desktops?','opts'=>['SDRAM','DDR3','DDR4','RDRAM'],'ans'=>2],
      ['q'=>'What is the purpose of a firewall?','opts'=>['Speed up internet','Control incoming and outgoing network traffic','Compress files','Back up data'],'ans'=>1],
      ['q'=>'Which device amplifies and regenerates network signals?','opts'=>['Hub','Switch','Repeater','Modem'],'ans'=>2],
      ['q'=>'What does "plug and play" mean?','opts'=>['Hardware that requires no drivers','Hardware recognized and configured automatically by the OS','Software that runs without installation','Wireless hardware'],'ans'=>1],
      ['q'=>'Which Windows tool is used to manage disk partitions?','opts'=>['Task Manager','Device Manager','Disk Management','Control Panel'],'ans'=>2],
      ['q'=>'What is the purpose of a checksum?','opts'=>['Encrypt files','Verify data integrity','Compress data','Allocate memory'],'ans'=>1],
      ['q'=>'Which type of malware disguises itself as legitimate software?','opts'=>['Worm','Ransomware','Trojan Horse','Spyware'],'ans'=>2],
    ],

    'networking' => [
      ['q'=>'What does OSI stand for?','opts'=>['Open System Interconnection','Operational System Interface','Open Software Integration','Operational Software Interconnect'],'ans'=>0],
      ['q'=>'How many layers does the OSI model have?','opts'=>['4','5','7','8'],'ans'=>2],
      ['q'=>'Which layer of the OSI model is responsible for routing?','opts'=>['Data Link','Transport','Network','Session'],'ans'=>2],
      ['q'=>'What is the subnet mask for a /24 network?','opts'=>['255.255.0.0','255.0.0.0','255.255.255.0','255.255.255.128'],'ans'=>2],
      ['q'=>'Which protocol is used to send email?','opts'=>['IMAP','POP3','SMTP','HTTP'],'ans'=>2],
      ['q'=>'What does MAC stand for in networking?','opts'=>['Media Access Control','Main Address Code','Memory Access Control','Media Address Command'],'ans'=>0],
      ['q'=>'Which device operates at the Data Link layer?','opts'=>['Router','Hub','Switch','Repeater'],'ans'=>2],
      ['q'=>'What is the default port for HTTPS?','opts'=>['80','21','443','8080'],'ans'=>2],
      ['q'=>'Which IP address range is reserved for private networks (Class C)?','opts'=>['10.0.0.0/8','172.16.0.0/12','192.168.0.0/16','169.254.0.0/16'],'ans'=>2],
      ['q'=>'What does ARP stand for?','opts'=>['Address Resolution Protocol','Automatic Route Protocol','Address Routing Process','Automatic Resolution Protocol'],'ans'=>0],
      ['q'=>'Which protocol is connection-oriented?','opts'=>['UDP','ICMP','TCP','IP'],'ans'=>2],
      ['q'=>'What is the maximum number of hosts in a /24 subnet?','opts'=>['254','255','256','253'],'ans'=>0],
      ['q'=>'Which command tests network connectivity?','opts'=>['tracert','nslookup','ping','ipconfig'],'ans'=>2],
      ['q'=>'What does VLAN stand for?','opts'=>['Virtual Local Area Network','Virtual Logical Access Node','Variable LAN','Virtual Link Area Node'],'ans'=>0],
      ['q'=>'Which layer of the TCP/IP model corresponds to the OSI Network layer?','opts'=>['Application','Transport','Internet','Network Access'],'ans'=>2],
      ['q'=>'What is the purpose of NAT?','opts'=>['Assign IP addresses','Translate private IPs to public IPs','Encrypt network traffic','Route packets between networks'],'ans'=>1],
      ['q'=>'Which protocol uses port 22?','opts'=>['FTP','Telnet','SSH','RDP'],'ans'=>2],
      ['q'=>'What type of cable uses light to transmit data?','opts'=>['Cat6','Coaxial','Fiber Optic','STP'],'ans'=>2],
      ['q'=>'What is the loopback IP address?','opts'=>['192.168.1.1','10.0.0.1','127.0.0.1','0.0.0.0'],'ans'=>2],
      ['q'=>'Which network topology connects all devices to a central hub?','opts'=>['Ring','Mesh','Bus','Star'],'ans'=>3],
      ['q'=>'What does DHCP stand for?','opts'=>['Dynamic Host Configuration Protocol','Direct Host Control Protocol','Dynamic Hardware Configuration Process','Direct Hardware Control Protocol'],'ans'=>0],
      ['q'=>'Which protocol resolves hostnames to IP addresses?','opts'=>['DHCP','ARP','DNS','NAT'],'ans'=>2],
      ['q'=>'What is the IPv6 address size?','opts'=>['32-bit','64-bit','128-bit','256-bit'],'ans'=>2],
      ['q'=>'Which protocol is used for secure web browsing?','opts'=>['HTTP','FTP','HTTPS','Telnet'],'ans'=>2],
      ['q'=>'What is a default gateway?','opts'=>['The fastest server on the network','A device that connects different networks','The first DNS server','The primary domain controller'],'ans'=>1],
      ['q'=>'Which command displays network configuration in Windows?','opts'=>['ifconfig','netstat','ipconfig','arp'],'ans'=>2],
      ['q'=>'What does QoS stand for?','opts'=>['Quality of Service','Quantity of Signals','Queue of Sessions','Quality of Security'],'ans'=>0],
      ['q'=>'Which layer handles end-to-end communication and error recovery?','opts'=>['Network','Data Link','Transport','Session'],'ans'=>2],
      ['q'=>'What is bandwidth in networking?','opts'=>['Signal strength','Maximum data transfer rate','Network latency','Number of connected devices'],'ans'=>1],
      ['q'=>'Which type of DNS record maps a domain to an IP address?','opts'=>['MX','CNAME','A','PTR'],'ans'=>2],
      ['q'=>'What is the purpose of ICMP?','opts'=>['Transfer files','Send emails','Report errors and diagnostics','Assign IP addresses'],'ans'=>2],
      ['q'=>'Which protocol is used to download email while leaving it on the server?','opts'=>['SMTP','POP3','IMAP','MIME'],'ans'=>2],
      ['q'=>'What is a broadcast address used for?','opts'=>['Send data to all hosts in a subnet','Connect to the internet','Identify the network','Identify the gateway'],'ans'=>0],
      ['q'=>'Which standard defines wireless LAN (Wi-Fi)?','opts'=>['IEEE 802.3','IEEE 802.11','IEEE 802.1Q','IEEE 802.1X'],'ans'=>1],
      ['q'=>'What does VPN stand for?','opts'=>['Virtual Private Network','Variable Public Node','Virtual Protocol Network','Variable Private Node'],'ans'=>0],
      ['q'=>'Which device forwards packets between networks based on IP addresses?','opts'=>['Switch','Hub','Bridge','Router'],'ans'=>3],
      ['q'=>'What is a DMZ in network security?','opts'=>['Demilitarized Zone — a network segment for public-facing servers','Domain Management Zone','Dynamic Management Zone','Dedicated Machine Zone'],'ans'=>0],
      ['q'=>'Which protocol provides reliable file transfer?','opts'=>['TFTP','UDP','FTP','ICMP'],'ans'=>2],
      ['q'=>'What is latency in networking?','opts'=>['Total bandwidth available','Delay in data transmission','Number of hops to destination','Signal frequency'],'ans'=>1],
      ['q'=>'Which layer of OSI is responsible for data encryption (SSL/TLS)?','opts'=>['Application','Presentation','Session','Transport'],'ans'=>1],
      ['q'=>'What is the purpose of Spanning Tree Protocol (STP)?','opts'=>['Prevent IP conflicts','Prevent switching loops','Assign VLANs','Route between subnets'],'ans'=>1],
      ['q'=>'Which command shows active TCP connections in Windows?','opts'=>['ipconfig','ping','netstat','tracert'],'ans'=>2],
      ['q'=>'What does SSID stand for?','opts'=>['Secure Signal Identification','Service Set Identifier','System Security ID','Sub-network System Identifier'],'ans'=>1],
      ['q'=>'What type of IP address is assigned by DHCP?','opts'=>['Static','Dynamic','Loopback','Broadcast'],'ans'=>1],
      ['q'=>'Which protocol is used for network time synchronization?','opts'=>['SNMP','NTP','LDAP','RADIUS'],'ans'=>1],
      ['q'=>'What is a proxy server?','opts'=>['A backup server','An intermediary between clients and servers','A server that assigns IPs','A DNS resolver'],'ans'=>1],
      ['q'=>'Which Wi-Fi security protocol is currently the most secure?','opts'=>['WEP','WPA','WPA2','WPA3'],'ans'=>3],
      ['q'=>'What is the purpose of a network switch?','opts'=>['Connect networks together','Connect devices within the same network using MAC addresses','Assign IP addresses','Filter traffic by IP'],'ans'=>1],
      ['q'=>'Which protocol is used by network monitoring tools?','opts'=>['FTP','HTTP','SNMP','Telnet'],'ans'=>2],
      ['q'=>'What is full-duplex communication?','opts'=>['Data flows in one direction','Data flows in both directions simultaneously','Data flows alternately in each direction','Data is broadcast to all'],'ans'=>1],
    ],

    'cybersecurity' => [
      ['q'=>'What does CIA stand for in cybersecurity?','opts'=>['Confidentiality, Integrity, Availability','Control, Identity, Access','Cyber Intelligence Agency','Confidential Information Archive'],'ans'=>0],
      ['q'=>'Which attack intercepts communication between two parties?','opts'=>['Phishing','DoS','Man-in-the-Middle','SQL Injection'],'ans'=>2],
      ['q'=>'What is the purpose of a firewall?','opts'=>['Speed up internet','Detect viruses','Control network traffic based on rules','Encrypt data'],'ans'=>2],
      ['q'=>'Which type of malware encrypts data and demands payment?','opts'=>['Spyware','Adware','Ransomware','Worm'],'ans'=>2],
      ['q'=>'What does two-factor authentication (2FA) add?','opts'=>['Faster login','An additional verification layer beyond password','Automatic password reset','Single sign-on capability'],'ans'=>1],
      ['q'=>'What is a phishing attack?','opts'=>['Flooding a server with requests','Tricking users into revealing credentials','Exploiting software vulnerabilities','Intercepting network traffic'],'ans'=>1],
      ['q'=>'Which encryption standard is currently considered secure for data?','opts'=>['DES','MD5','AES-256','SHA-1'],'ans'=>2],
      ['q'=>'What is social engineering in cybersecurity?','opts'=>['Building secure networks','Manipulating people to divulge information','Writing secure code','Encrypting communications'],'ans'=>1],
      ['q'=>'What does a VPN primarily protect?','opts'=>['Your device from viruses','Your internet traffic and identity','Your files from deletion','Your device from physical theft'],'ans'=>1],
      ['q'=>'Which attack overwhelms a server with traffic?','opts'=>['SQL Injection','XSS','DoS/DDoS','Phishing'],'ans'=>2],
      ['q'=>'What is a zero-day vulnerability?','opts'=>['A vulnerability patched immediately','An unknown vulnerability with no patch available','A vulnerability in old systems','A deliberate backdoor'],'ans'=>1],
      ['q'=>'Which tool is used to scan for open ports?','opts'=>['Wireshark','Nmap','Metasploit','Burp Suite'],'ans'=>1],
      ['q'=>'What does HTTPS ensure?','opts'=>['Faster browsing','Encrypted connection between browser and server','Anonymous browsing','No tracking'],'ans'=>1],
      ['q'=>'What is a brute force attack?','opts'=>['Guessing passwords systematically','Injecting malicious code','Intercepting traffic','Social manipulation'],'ans'=>0],
      ['q'=>'Which password practice is most secure?','opts'=>['Using the same complex password everywhere','Short memorable passwords','Long random unique passwords with a manager','Writing passwords in a notebook'],'ans'=>2],
      ['q'=>'What is SQL injection?','opts'=>['A database performance technique','Inserting malicious SQL code into input fields','A method to back up databases','A database encryption method'],'ans'=>1],
      ['q'=>'What does the principle of least privilege mean?','opts'=>['Give all users admin access','Users get only the access they need for their job','Encrypt all data','Change passwords frequently'],'ans'=>1],
      ['q'=>'Which protocol provides secure remote access?','opts'=>['Telnet','FTP','HTTP','SSH'],'ans'=>3],
      ['q'=>'What is a honeypot in cybersecurity?','opts'=>['A malware type','A decoy system to attract attackers','A type of firewall','An intrusion prevention system'],'ans'=>1],
      ['q'=>'What is cross-site scripting (XSS)?','opts'=>['A CSS styling technique','Injecting malicious scripts into web pages viewed by others','Copying data across servers','A server configuration method'],'ans'=>1],
      ['q'=>'What does IDS stand for?','opts'=>['Internet Defense System','Intrusion Detection System','Internal Data Security','Internet Data Service'],'ans'=>1],
      ['q'=>'Which of the following is an example of multi-factor authentication?','opts'=>['Username and password','Password and security question','Password and fingerprint scan','PIN and password'],'ans'=>2],
      ['q'=>'What is a digital certificate used for?','opts'=>['Encrypt files locally','Verify the identity of websites/entities','Speed up SSL connections','Store passwords'],'ans'=>1],
      ['q'=>'What is steganography?','opts'=>['Encrypting data','Hiding data within other data or media','Network packet analysis','Password hashing'],'ans'=>1],
      ['q'=>'What does SIEM stand for?','opts'=>['Security Information and Event Management','System Integrity and Error Monitoring','Secure Internet Event Management','System Information and Event Monitor'],'ans'=>0],
      ['q'=>'Which type of malware replicates itself across networks without user action?','opts'=>['Virus','Trojan','Worm','Spyware'],'ans'=>2],
      ['q'=>'What is patch management?','opts'=>['Fixing physical server damage','Regularly updating software to fix vulnerabilities','Testing new software','Monitoring network traffic'],'ans'=>1],
      ['q'=>'Which hashing algorithm is recommended for storing passwords?','opts'=>['MD5','SHA-1','bcrypt','CRC32'],'ans'=>2],
      ['q'=>'What is a buffer overflow attack?','opts'=>['Sending too many emails','Overwriting memory adjacent to a buffer to execute code','Encrypting too much data','Flooding a network'],'ans'=>1],
      ['q'=>'What does the term "payload" mean in malware?','opts'=>['The malware\'s file size','The malicious action the malware performs','The malware\'s delivery method','The malware\'s source code'],'ans'=>1],
      ['q'=>'What is the purpose of a security audit?','opts'=>['Speed up systems','Evaluate security controls and identify weaknesses','Install new software','Monitor user behavior only'],'ans'=>1],
      ['q'=>'Which attack exploits trust between computers?','opts'=>['Phishing','IP Spoofing','Session Hijacking','Shoulder Surfing'],'ans'=>1],
      ['q'=>'What does PKI stand for?','opts'=>['Private Key Infrastructure','Public Key Infrastructure','Protected Key Integrity','Public Key Integration'],'ans'=>1],
      ['q'=>'What is the main purpose of antivirus software?','opts'=>['Speed up the computer','Back up files','Detect and remove malware','Block network traffic'],'ans'=>2],
      ['q'=>'What is a man-in-the-browser attack?','opts'=>['Physical access to a computer','Malware intercepting browser sessions','A phishing website','A DoS attack'],'ans'=>1],
      ['q'=>'What does OWASP stand for?','opts'=>['Online Web Application Security Project','Open Web Application Security Project','Official Web Access Security Protocol','Open Website Attack Security Platform'],'ans'=>1],
      ['q'=>'Which type of attack targets the human element rather than technology?','opts'=>['SQL Injection','Buffer Overflow','Social Engineering','XSS'],'ans'=>2],
      ['q'=>'What is a security token?','opts'=>['A password hint','A physical or digital device that generates authentication codes','A type of firewall','An encrypted file'],'ans'=>1],
      ['q'=>'What is the purpose of data encryption at rest?','opts'=>['Speed up data access','Protect data stored on disk from unauthorized access','Enable faster backups','Allow remote access'],'ans'=>1],
      ['q'=>'What does "defense in depth" mean?','opts'=>['Using only one very strong security layer','Using multiple overlapping security layers','Focusing only on network security','Encrypting everything'],'ans'=>1],
      ['q'=>'What is clickjacking?','opts'=>['A type of DDoS attack','Tricking users into clicking hidden malicious elements','A keylogger technique','A SQL injection variant'],'ans'=>1],
      ['q'=>'Which protocol provides secure file transfer?','opts'=>['FTP','HTTP','SFTP','Telnet'],'ans'=>2],
      ['q'=>'What is the role of a Certificate Authority (CA)?','opts'=>['Issue IP addresses','Issue and verify digital certificates','Monitor network traffic','Store encrypted passwords'],'ans'=>1],
      ['q'=>'What is the purpose of network segmentation?','opts'=>['Increase network speed','Limit the spread of attacks by isolating network sections','Assign more IP addresses','Enable VPN access'],'ans'=>1],
      ['q'=>'What is a rootkit?','opts'=>['A type of firewall','Malware that hides itself and gives persistent privileged access','A network scanner','An antivirus tool'],'ans'=>1],
      ['q'=>'What does GDPR stand for?','opts'=>['General Data Protection Regulation','Global Data Privacy Rights','General Digital Privacy Rules','Government Data Protection Requirements'],'ans'=>0],
      ['q'=>'What is the purpose of a DMZ in network security?','opts'=>['Store internal databases','Host public-facing services while isolating internal network','Block all external traffic','Assign dynamic IP addresses'],'ans'=>1],
      ['q'=>'What is a logic bomb?','opts'=>['A type of DoS attack','Malicious code triggered by a specific condition or event','A network vulnerability','A password cracking tool'],'ans'=>1],
      ['q'=>'Which principle states that security should not rely on obscurity?','opts'=>['Least Privilege','Defense in Depth','Kerckhoffs\'s Principle','Zero Trust'],'ans'=>2],
      ['q'=>'What is the main goal of penetration testing?','opts'=>['Install security patches','Simulate attacks to find vulnerabilities before attackers do','Monitor user activity','Encrypt sensitive data'],'ans'=>1],
    ],

    'software_installation' => [
    ['q'=>'What is the first step after identifying a need for software?','opts'=>['Install the software','Create a requirement specification','Buy hardware','Contact vendors'],'ans'=>1],
    ['q'=>'Which of the following is a source of software information?','opts'=>['Computer magazines','Internet','IT consultants','All of the above'],'ans'=>3],
    ['q'=>'What document is usually used in large organizations to request software purchases?','opts'=>['Invoice','Purchase Requisition','License Key','Warranty Card'],'ans'=>1],
    ['q'=>'Before installing software, you should first ensure that the computer satisfies what?','opts'=>['Color settings','System requirements','Network speed','Printer settings'],'ans'=>1],
    ['q'=>'Which of the following is considered a system requirement?','opts'=>['Minimum RAM size','Operating system','Disk space','All of the above'],'ans'=>3],
    ['q'=>'What are software prerequisites?','opts'=>['Games installed on the PC','Conditions needed for software to run correctly','Types of antivirus','Backup files'],'ans'=>1],
    ['q'=>'Which of the following may be a software prerequisite?','opts'=>['Internet connection','Security services','Prior installation of another software','All of the above'],'ans'=>3],
    ['q'=>'What are system incompatibilities?','opts'=>['Matching hardware','Conflicts between software and system configuration','Internet problems','Virus attacks'],'ans'=>1],
    ['q'=>'Which operating system is commonly required by software applications?','opts'=>['Windows','Unix','Macintosh','All of the above'],'ans'=>3],
    ['q'=>'What information should vendors provide about their software?','opts'=>['System requirements','Licensing details','Support services','All of the above'],'ans'=>3],
    ['q'=>'What is software licensing?','opts'=>['A hardware installation process','A legal agreement governing software use','A backup method','A networking tool'],'ans'=>1],
    ['q'=>'A software license key usually consists of what?','opts'=>['Pictures','Numbers and letters','Videos','Folders'],'ans'=>1],
    ['q'=>'What is software piracy?','opts'=>['Legal software use','Illegal copying of software','Updating applications','Scanning files'],'ans'=>1],
    ['q'=>'Which of the following is a legal reason for copying software?','opts'=>['Selling copies','Distributing to friends','Making one backup copy','Uploading online'],'ans'=>2],
    ['q'=>'What does copyright protect?','opts'=>['Electricity','Intellectual property','Internet access','Computer hardware'],'ans'=>1],
    ['q'=>'Which type of software requires registration information before use?','opts'=>['Freeware','Registerware','Open Source','Abandonware'],'ans'=>1],
    ['q'=>'Which software is distributed on a trial basis?','opts'=>['Shareware','Freeware','Open Source','Registerware'],'ans'=>0],
    ['q'=>'What is freeware?','opts'=>['Software available at no cost','Illegal software','Software requiring registration','Software for servers only'],'ans'=>0],
    ['q'=>'Open Source Software allows users to do what?','opts'=>['Only view software','Use, modify, and redistribute software','Only purchase licenses','Prevent modifications'],'ans'=>1],
    ['q'=>'What is abandonware?','opts'=>['Damaged software','Software no longer available for purchase','Free antivirus','Operating systems'],'ans'=>1],
    ['q'=>'What is a click-wrap license?','opts'=>['A network agreement','A license accepted by clicking accept during installation','A printed manual','A software virus'],'ans'=>1],
    ['q'=>'Which detail should be documented after software installation?','opts'=>['Version number','License number','Installation date','All of the above'],'ans'=>3],
    ['q'=>'Why is documenting licensing details important?','opts'=>['It proves legal software use','Simplifies troubleshooting','Records installations','All of the above'],'ans'=>3],
    ['q'=>'What is a software installation wizard?','opts'=>['A hardware tool','A program that simplifies installation','An antivirus','A backup system'],'ans'=>1],
    ['q'=>'What does a Readme.txt file usually contain?','opts'=>['Movies','Extra software information','Music files','Passwords'],'ans'=>1],
    ['q'=>'What is the role of Help Desk Staff?','opts'=>['Repair hardware only','Provide timely advice to users','Sell software','Create viruses'],'ans'=>1],
    ['q'=>'What does upgrading software mean?','opts'=>['Removing software','Replacing with a newer version','Formatting a drive','Changing hardware only'],'ans'=>1],
    ['q'=>'Which of the following is a risk of upgrading software?','opts'=>['Improved performance','Hardware incompatibility','More disk space','Faster internet'],'ans'=>1],
    ['q'=>'What type of software upgrades should usually be installed quickly?','opts'=>['Old versions','Bug fixes and service releases','Games','Unstable software'],'ans'=>1],
    ['q'=>'Why should users sometimes wait before installing major upgrades?','opts'=>['To avoid bugs and compatibility problems','To increase costs','To delete files','To remove RAM'],'ans'=>0],
    ['q'=>'What is a portable application?','opts'=>['Software requiring installation','Software that runs without installation','Software only for laptops','Mobile apps'],'ans'=>1],
    ['q'=>'What may occur during software installation?','opts'=>['Creating folders','Adding registry entries','Creating shortcuts','All of the above'],'ans'=>3],
    ['q'=>'Why is checking the operating system important before installation?','opts'=>['To change wallpapers','To ensure compatibility','To increase brightness','To disable USB ports'],'ans'=>1],
    ['q'=>'What should you do with compressed .ZIP or .RAR files before installation?','opts'=>['Delete them','Uncompress them','Rename them','Encrypt them'],'ans'=>1],
    ['q'=>'What should be closed before installing software?','opts'=>['All other programs','The monitor','The keyboard','The mouse'],'ans'=>0],
    ['q'=>'Which type of installation shows no messages during progress?','opts'=>['Clean installation','Silent installation','Network installation','Flat installation'],'ans'=>1],
    ['q'=>'What is an unattended installation?','opts'=>['Installation requiring constant interaction','Installation with little or no user interaction','Installation from DVD only','Online installation'],'ans'=>1],
    ['q'=>'What is a clean installation?','opts'=>['Installation without interference from old files or issues','Installing antivirus','Formatting the monitor','Installing updates only'],'ans'=>0],
    ['q'=>'What is a flat installation?','opts'=>['Installation from copied files on a hard drive','Installing software upside down','Cloud installation','Remote repair'],'ans'=>0],
    ['q'=>'What is a network installation?','opts'=>['Installation from a shared network drive','Installing drivers','Internet browsing','Creating backups'],'ans'=>0],
    ['q'=>'When should software installation ideally occur to minimize disruption?','opts'=>['During busy office hours','During quiet periods or after office hours','During meetings','At lunch breaks only'],'ans'=>1],
    ['q'=>'What software can help install the same applications on multiple computers quickly?','opts'=>['Firewall software','Cloning software','Spreadsheet software','Compression software'],'ans'=>1],
    ['q'=>'What should be organized before installation begins?','opts'=>['Troubleshooting disks','License numbers','Backup disks','All of the above'],'ans'=>3],
    ['q'=>'Which basic software functions should be tested after installation?','opts'=>['Starting','Operating','Closing','All of the above'],'ans'=>3],
    ['q'=>'What is the responsibility of a Computer Support Officer?','opts'=>['Install and test software','Sell computers','Create viruses','Manage electricity'],'ans'=>0],
    ['q'=>'Why should software demonstrations be planned in advance?','opts'=>['To avoid mistakes','To waste time','To uninstall software','To reduce RAM'],'ans'=>0],
    ['q'=>'Who is responsible for training staff in the use of new software?','opts'=>['Security guard','Staff Trainer','Receptionist','Accountant'],'ans'=>1],
    ['q'=>'What may customers assume if software problems occur after installation?','opts'=>['The software is perfect','The installer is responsible','The monitor is broken','The printer failed'],'ans'=>1],
    ['q'=>'Which option installs a program later after downloading the setup file?','opts'=>['Open','Run','Save','Delete'],'ans'=>2],
    ['q'=>'Which Windows Control Panel option is used to uninstall programs?','opts'=>['Disk Cleanup','Programs and Features','Task Manager','Device Manager'],'ans'=>1],
],

'sql_basics' => [
    ['q'=>'What does SQL stand for?','opts'=>['Structured Query Language','Simple Query Language','Sequential Query Logic','System Query Language'],'ans'=>0],
    ['q'=>'What is the purpose of Data Definition Language (DDL)?','opts'=>['Retrieve data','Define and manage database structure','Insert records','Delete rows'],'ans'=>1],
    ['q'=>'Which SQL command is used to create a database?','opts'=>['MAKE DATABASE','NEW DATABASE','CREATE DATABASE','BUILD DATABASE'],'ans'=>2],
    ['q'=>'Which SQL command removes a table permanently?','opts'=>['DELETE TABLE','REMOVE TABLE','DROP TABLE','CLEAR TABLE'],'ans'=>2],
    ['q'=>'What does the ALTER TABLE command do?','opts'=>['Delete a database','Modify table structure','Insert records','Create indexes only'],'ans'=>1],
    ['q'=>'Which database object contains rows and columns?','opts'=>['Schema','Catalog','Table','Cluster'],'ans'=>2],
    ['q'=>'Schemas contain which database objects?','opts'=>['Rows only','Tables and views','Columns only','Indexes only'],'ans'=>1],
    ['q'=>'What contains schemas in a relational database?','opts'=>['Columns','Catalogs','Views','Rows'],'ans'=>1],
    ['q'=>'What is a primary key?','opts'=>['A duplicate value','A unique identifier for records','A backup column','A calculated field'],'ans'=>1],
    ['q'=>'What is the purpose of a foreign key?','opts'=>['Encrypt data','Link tables together','Store passwords','Delete records'],'ans'=>1],
    ['q'=>'Which SQL command is used to create a table?','opts'=>['MAKE TABLE','NEW TABLE','CREATE TABLE','BUILD TABLE'],'ans'=>2],
    ['q'=>'Which normal form helps prevent insertion, deletion, and update anomalies?','opts'=>['1NF','2NF','3NF','4NF'],'ans'=>2],
    ['q'=>'What should every table in a database have?','opts'=>['At least one image','A primary key','Two databases','Multiple schemas'],'ans'=>1],
    ['q'=>'According to ANSI/ISO standards, SQL names should begin with what?','opts'=>['A number','A special character','A letter','A symbol'],'ans'=>2],
    ['q'=>'Which datatype stores fixed-length character strings?','opts'=>['varchar','char','text','image'],'ans'=>1],
    ['q'=>'Which datatype stores variable-length character strings?','opts'=>['char','varchar','binary','money'],'ans'=>1],
    ['q'=>'Which datatype is used for Unicode variable-length data?','opts'=>['varchar','nvarchar','binary','datetime'],'ans'=>1],
    ['q'=>'Which datatype allows values 0, 1, or NULL?','opts'=>['bit','float','real','money'],'ans'=>0],
    ['q'=>'Which datatype stores whole numbers from 0 to 255?','opts'=>['smallint','int','tinyint','bigint'],'ans'=>2],
    ['q'=>'Which datatype is commonly used for exact monetary values?','opts'=>['float','money','real','binary'],'ans'=>1],
    ['q'=>'Which datatype stores date only?','opts'=>['datetime','time','date','timestamp'],'ans'=>2],
    ['q'=>'Which datatype stores time only?','opts'=>['time','date','datetime','timestamp'],'ans'=>0],
    ['q'=>'What does NULL represent in SQL?','opts'=>['Zero value','Blank string','Missing or unknown data','Negative value'],'ans'=>2],
    ['q'=>'Which SQL constraint prevents NULL values in a column?','opts'=>['UNIQUE','CHECK','NOT NULL','DEFAULT'],'ans'=>2],
    ['q'=>'Which constraint ensures all values in a column are unique?','opts'=>['CHECK','DEFAULT','UNIQUE','NULL'],'ans'=>2],
    ['q'=>'How many PRIMARY KEY constraints can a table have?','opts'=>['One','Two','Unlimited','Zero'],'ans'=>0],
    ['q'=>'Which constraint inserts a default value if no value is provided?','opts'=>['CHECK','DEFAULT','PRIMARY KEY','UNIQUE'],'ans'=>1],
    ['q'=>'What does the CHECK constraint do?','opts'=>['Deletes records','Validates entered values','Encrypts columns','Creates views'],'ans'=>1],
    ['q'=>'Which keyword is used in SQL Server for auto-increment fields?','opts'=>['AUTO','AUTOINCREMENT','IDENTITY','INCREMENT'],'ans'=>2],
    ['q'=>'What is a view in SQL?','opts'=>['A physical table','A virtual table','A backup file','A database server'],'ans'=>1],
    ['q'=>'What command adds a primary key after a table already exists?','opts'=>['ALTER TABLE ADD PRIMARY KEY','CREATE PRIMARY KEY','INSERT PRIMARY KEY','MODIFY KEY'],'ans'=>0],
    ['q'=>'Which datatype stores XML formatted data?','opts'=>['text','xml','binary','ntext'],'ans'=>1],
    ['q'=>'Which datatype stores globally unique identifiers?','opts'=>['timestamp','uniqueidentifier','real','cursor'],'ans'=>1],
    ['q'=>'What is the maximum number of characters for char(n)?','opts'=>['255','4000','8000','2GB'],'ans'=>2],
    ['q'=>'What is the purpose of database planning?','opts'=>['Increase internet speed','Ensure proper database structure','Delete duplicate files','Format hard drives'],'ans'=>1],
    ['q'=>'Which SQL statement is used to insert records into a table?','opts'=>['PUT INTO','ADD RECORD','INSERT INTO','CREATE RECORD'],'ans'=>2],
    ['q'=>'How are string constants enclosed in SQL?','opts'=>['Double quotes','Square brackets','Single quotes','Parentheses'],'ans'=>2],
    ['q'=>'Which datatype stores floating precision numbers?','opts'=>['money','float','char','binary'],'ans'=>1],
    ['q'=>'Which datatype stores a unique number updated whenever a row changes?','opts'=>['timestamp','datetime','real','float'],'ans'=>0],
    ['q'=>'What is the purpose of expressions in SQL?','opts'=>['Design websites','Calculate values','Install software','Create backups'],'ans'=>1],
    ['q'=>'Which SQL command retrieves data from a database?','opts'=>['SELECT','CREATE','DROP','ALTER'],'ans'=>0],
    ['q'=>'What is the role of a schema in SQL?','opts'=>['Stores rows only','Contains tables and views','Deletes records','Creates backups'],'ans'=>1],
    ['q'=>'Which datatype is best for storing percentages exactly?','opts'=>['decimal','float','real','binary'],'ans'=>0],
    ['q'=>'What is the default starting value for IDENTITY in SQL Server?','opts'=>['0','1','5','10'],'ans'=>1],
    ['q'=>'What does SQL support explicitly for missing data?','opts'=>['Empty strings','Null values','Zero values','False values'],'ans'=>1],
    ['q'=>'What type of relationship exists when a foreign key references another table’s primary key?','opts'=>['Logical relationship','Binary relationship','Temporary relationship','Virtual relationship'],'ans'=>0],
    ['q'=>'Which SQL object is considered a virtual table?','opts'=>['Index','View','Schema','Catalog'],'ans'=>1],
    ['q'=>'What does the DEFAULT GETDATE() function insert?','opts'=>['Current system date','Random number','Primary key','Null value'],'ans'=>0],
    ['q'=>'Which datatype stores binary data up to 2GB?','opts'=>['binary','image','tinyint','real'],'ans'=>1],
    ['q'=>'Which SQL feature allows multiple computers to simulate workloads in SQL Server?','opts'=>['Distributed Replay','Data Mirroring','Cluster Backup','Schema Mapping'],'ans'=>0],
],
    ];

    return $allExams[$examId] ?? [];
}

$examNames = [
    'it_fundamentals' => 'IT Fundamentals',
    'networking'      => 'Computer Networking',
    'cybersecurity'   => 'Cybersecurity Basics',
    'software_installation' => 'Software Installation',
    'sql_basics' => 'Sql Basics',
];
